version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - wordpress
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    env_file: .env
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: $HOME/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: $HOME/data/mariadb
      o: bind
      type: none
